project:
  type: website
  output-dir: docs

website:
  title: "Tzu-Yao's Blog"
  site-url: https://xup6y3ul6.github.io
  description: "Tzu-Yao's Psychology and Data Sciences World"
  #google-analytics: ""
  navbar:
    left:
      - href: blog.qmd
        text: "Posts"
      - href: project.qmd
        text: "Projects"
      - text: "Research"
        menu: 
          - text: "Publications"
            href: research/publication.qmd
          - text: "Presentations"
            href: research/presentation.qmd
    right:
      - href: about.qmd
        text: "About Me"
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/xup6y3ul6
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

editor: source

