project:
  type: website

website:
  title: "Tzu-Yao Lin"
  #site-url: https://www.myblogexample.io
  #description: "A great sample blog"
  #google-analytics: ""
  navbar:
    right:
      - href: about.qmd
        text: "About"
      - href: blog.qmd
        text: "Posts"
      - href: project.qmd
        text: "Projects"
      - text: "Research"
        menu: 
          - text: "Papers"
            href: research/papers.qmd
          - text: "Presentations"
            href: research/presentations.qmd
      - icon: rss
        href: index.xml
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

